### ISSUE TITLE
Proposed improvements

### ISSUE THREAD

**Issue by steven0seagal** [hch155/signal-scout#93]
List of possible improvements you could make for app:
- migrate database to postgresql ( dockerfile + docker-compose)
- move all scripts from root to one direcory ( src/scripts)
- upgrade python to 3.11/3.12 - it will increase execution of code
- add ranges of base stations 
- think if it possible to make algorithm to calculate signal strengths based on topographical data (i.e after pointing some place on map, list of near base stations appear below and based on what is located on distance between base station calculate approximately signal strength)  
- i think loop function on map is not necessary because it zoom in/out and above are minus and plus that makes the same
- after resetting filters when location is selected no base stations appear 
- sometimes after pointing some location on map, zooming in does not work 
- solve slow loading data on map ( ~5 sec after clicking on map ), get time of loading data after selecting locations it should take in ms not seconds 
-  add function to map that will allow add geographical data as form below and then shows what base stations are near
- ... TBC

**Comment by hch155** [comment]
> _List of possible improvements you could make for app:_
> 
>     * migrate database to postgresql ( dockerfile + docker-compose)
tested, currently not planning, considering various options right now
> 
>     * move all scripts from root to one direcory ( src/scripts)
done, PR #94 
>     * upgrade python to 3.11/3.12 - it will increase execution of code
done, PR #102 
>     * add ranges of base stations
done, PR #103, #104, #105, #106
>     * think if it possible to make algorithm to calculate signal strengths based on topographical data (i.e after pointing some place on map, list of near base stations appear below and based on what is located on distance between base station calculate approximately signal strength)
done, PR #109, #111
>     * i think loop function on map is not necessary because it zoom in/out and above are minus and plus that makes the same
done, PR #94 
>     * after resetting filters when location is selected no base stations appear
done, PR #96 
>     * sometimes after pointing some location on map, zooming in does not work
issue did not reoccur, would need some video of it
>     * solve slow loading data on map ( ~5 sec after clicking on map ), get time of loading data after selecting locations it should take in ms not seconds

done, PR #108, #116, further enhancements feasible and planned, currently:

I. LOCAL env:

without filters:
AVG response time: 0.558 seconds
MAX response time: 0.934 seconds
MIN response time: 0.378 seconds

with filters:
AVG response time: 0.132 seconds
MAX response time: 0.246 seconds
MIN response time: 0.087 seconds

II.  PROD env:

without filters:
AVG response time: 0.952 seconds
MAX response time: 1.182 seconds
MIN response time: 0.757 seconds

with filters:
AVG response time: 0.419 seconds
MA response time: 0.477 seconds
MIN response time: 0.327 seconds

>     * add function to map that will allow add geographical data as form below and then shows what base stations are near
this feature was implemented in PR #68, which is meant for registered/logged in users

thank you for the input!
